name: Bug Report
description: Report a Bug or an Issue with this Addon.
labels: []

body:
  - id: checklist
    type: checkboxes
    attributes:
      label: 'Checklist'
      description: Please go through this checklist before creating the issue.
      options:
        - label: I am using the official english version of Slimefun and did not modify the jar.
          required: true
        - label: I am using an up to date "DEV" (not "RC") version of Slimefun.
          required: true
        - label: I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
          required: true
        - label: I searched for similar open issues and could not find an existing bug report on this.
          required: true

  - id: description
    type: textarea
    validations:
      required: true
    attributes:
      label: 'Description'

  - id: reproduction-steps
    type: textarea
    validations:
      required: true
    attributes:
      label: 'Reproduction Steps'

  - id: expected-behaviour
    type: textarea
    validations:
      required: true
    attributes:
      label: 'Expected Behavior'

  - id: media
    type: textarea
    attributes:
      label: 'Screenshots / Videos'

  - id: server-log
    type: input
    attributes:
      label: 'Server Log'

  - id: error-reports
    type: input
    attributes:
      label: '`/error-reports/` folder'

  - id: server-software
    type: dropdown
    validations:
      required: true
    attributes:
      label: 'Server Software'
      options:
        - Spigot
        - Paper
        - Tuinity
        - Yatopia
        - Purpur
        - Airplane
        - Other (please specify in your description)

  - id: minecraft-version
    type: dropdown
    validations:
      required: true
    attributes:
      label: 'Minecraft Version'
      options:
        - 1.16.x
        - (Older versions are not supported)

  - id: slimefun-version
    type: textarea
    validations:
      required: true
    attributes:
      label: 'Slimefun version'

  - id: other-versions
    type: textarea
    attributes:
      label: 'Other plugins'